service: lambda-test

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::lambda-test-dev-serverlessdeploymentbucket-80wk506elytf/*"
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: users/create
         method: get
  imageResize:
    handler: image.resizeImage
    events:
     - http:
         path: image/resize
         method: get
  userLogin:
    handler: user/auth.auth
    events:
     - http:
         path: user/login
         method: get
